[project]
name = "learning-rf"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "robotframework>=7.3.2",
    "robotframework-jsonlibrary>=0.5",
    "robotframework-requests>=0.9.7",
]
